server:
  port:8080
management:
  server:
    port:8090
  endpoints:
    web:
      expose:"*"

  endpoint:
    shutdown:
      enabled:true


spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false